# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build the joint classification/regression forest
#' 
#' @param x A single integer.
#' @export
build_jcr_forest <- function(x, ntree, maxnodes) {
    .Call('JCRForest_build_jcr_forest', PACKAGE = 'JCRForest', x, ntree, maxnodes)
}

